added loading until the API request resolve
Mahmoudgalalz/JuniorJobs pull request #64
Opened 2023-02-25 20:22 UTC by EL-Gazoly

I have included a loading spinner feature. The loading spinner will be displayed until the request has been fully resolved

ps: for some reason, my pic won't appear probably in the about page I think you are cropping your pics with some tool that worked for you but it does not work with me for some reason

2023-02-25 22:27 UTC, Mahmoudgalalz commented on src/pages/opportunities/index.astro
> +<SearchBar id="searchBar"/>
I think you can not use id here, remove it

2023-02-25 22:29 UTC, EL-Gazoly commented on src/pages/opportunities/index.astro
> +<SearchBar id="searchBar"/>
Yup I was just trying something out

2023-02-25 22:30 UTC, Mahmoudgalalz requested changes
and I want the whole page to be in the reload mode,
![image](https://user-images.githubusercontent.com/42272376/221382471-fb314e98-5591-4596-8719-41326c316ff7.png)
this is a scratch, so you can understand what I'm saying

2023-02-25 22:31 UTC, Mahmoudgalalz commented on src/pages/opportunities/index.astro
> +<SearchBar id="searchBar"/>
I was doing the same, but its return null, as it's not an HTML class component :joy:

2023-02-25 22:34 UTC, EL-Gazoly commented
See I was going to do that but I thought the search bar is static it won't change so why load it again only the data needed to be loaded depending on the query

2023-02-25 22:37 UTC, Mahmoudgalalz commented
> See I was going to do that but I thought the search bar is static it won't change so why load it again only the data needed to be loaded depending on the query

way may consider it, like that, but I prefer that, cuz may he will search before loading, so I'm forcing him to wait

and leave the current loading when he click on the search, we will use it

2023-02-25 22:48 UTC, EL-Gazoly commented
Okay, as you like, I will start working on it

2023-02-25 22:51 UTC, EL-Gazoly commented on src/pages/opportunities/index.astro
> +<SearchBar id="searchBar"/>
Yup  you have to surround it on another div tag for example and call that div

2023-02-27 01:06 UTC, merged

2023-02-27 01:22 UTC, Mahmoudgalalz approved these changes
Perfect, I added some adjustments